import React, { useState } from "react";
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InteriorDesign from "@/components/Interiordesign";
import Popup from "@/components/Popup";
import styles from "../src/styles/pages/Projects.module.scss";

export default function Projects() {
  const [popupVisible, setPopupVisible] = useState(false);
  const [selectedEventData, setSelectedEventData] = useState(null);

  const eventsData = [
    {
        attributes: {
            imageSrc: "/img/bannerimg1.jpg",
            venue: "Venue Name 1",
            date: "2024-07-21",
            title: "Site 1",
            description: "<p>Some description for event 1.</p>",
            eventImages: {
                data: [
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                ],
            },
        },
    },
    {
        attributes: {
            imageSrc: "/img/bannerimg1.jpg",
            venue: "Venue Name 2",
            date: "2024-08-15",
            title: "Site 2",
            description: "<p>Some description for event 2.</p>",
            eventImages: {
                data: [
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                ],
            },
        },
    },{
      attributes: {
          imageSrc: "/img/bannerimg1.jpg",
          venue: "Venue Name 3",
          date: "2024-08-15",
          title: "Site 3",
          description: "<p>Some description for event 2.</p>",
          eventImages: {
              data: [
                  { attributes: { url: "/img/good-company/img_4.jpg" } },
                  { attributes: { url: "/img/good-company/img_4.jpg" } },
                  { attributes: { url: "/img/good-company/img_4.jpg" } },
                  { attributes: { url: "/img/good-company/img_4.jpg" } },
                  { attributes: { url: "/img/good-company/img_4.jpg" } },
              ],
          },
      },     
  },{
    attributes: {
        imageSrc: "/img/bannerimg1.jpg",
        venue: "Venue Name 3",
        date: "2024-08-15",
        title: "Site 3",
        description: "<p>Some description for event 2.</p>",
        eventImages: {
            data: [
                { attributes: { url: "/img/good-company/img_4.jpg" } },
                { attributes: { url: "/img/good-company/img_4.jpg" } },
                { attributes: { url: "/img/good-company/img_4.jpg" } },
                { attributes: { url: "/img/good-company/img_4.jpg" } },
                { attributes: { url: "/img/good-company/img_4.jpg" } },
            ],
        },
    },     
}
    // Add more events here as needed
  ];

  // Updated to take the specific event's data
  const handleInteriorDesignClick = (eventData) => {
    setSelectedEventData(eventData);
    setPopupVisible(true);
  };

  const handleClosePopup = () => {
    setPopupVisible(false);
    setSelectedEventData(null);
  };

  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={`${styles.index_page} bg_secondary`}>
        <div className="container">
          <div className="font_primary text_3xl">Interior Design</div>
          <div className={styles.maindata}>
            {eventsData.map((eventData, index) => (
              <InteriorDesign
                key={index} // Unique key for each item
                eventsData={eventData.attributes} // Pass the event attributes
                onClick={() => handleInteriorDesignClick(eventData.attributes)} // Pass the clicked event's data
              />
            ))}

            {popupVisible && (
              <Popup
                data={selectedEventData} // Pass the selected event data to the popup
                onClose={handleClosePopup}
                popupVisible={popupVisible}
                setPopupVisible={setPopupVisible}
              />
            )}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
