import React, { useState } from "react";
import Head from "next/head";
import Footer from "../src/components/Footer";
import Header from "../src/components/Header";
import InteriorDesign from "@/components/Interiordesign";
import Popup from "@/components/Popup";
import styles from "../src/styles/pages/Projects.module.scss";

export default function Projects() {
  const [popupVisible, setPopupVisible] = useState(false);
  const [selectedEventData, setSelectedEventData] = useState(null);

  const eventsData = [
    {
        attributes: {
            imageSrc: "/img/bannerimg1.jpg",
            venue: "Venue Name 1",
            date: "2024-07-21",
            title: "Siddharth Title 1",
            description: "<p>Some description for event 1.</p>",
            eventImages: {
                data: [
                    { attributes: { url: "/img/good-company/img_1.jpg" } },
                    { attributes: { url: "/img/good-company/img_2.jpg" } },
                ],
            },
        },
    },
    {
        attributes: {
            imageSrc: "/img/bannerimg1.jpg",
            venue: "Venue Name 2",
            date: "2024-08-15",
            title: "Siddharth Title 2",
            description: "<p>Some description for event 2.</p>",
            eventImages: {
                data: [
                    { attributes: { url: "/img/good-company/img_3.jpg" } },
                    { attributes: { url: "/img/good-company/img_4.jpg" } },
                ],
            },
        },
    },
    // Ensure all objects in the array have the same structure
];


  const handleInteriorDesignClick = () => {
    setSelectedEventData(eventsData.attributes);
    setPopupVisible(true);
  };

  const handleClosePopup = () => {
    setPopupVisible(false);
    setSelectedEventData(null);
  };

  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={`${styles.index_page} bg_secondary`}>
        <div className="container">
          <div className="font_primary text_3xl">Interior Design</div>
          <div className={styles.maindata}>
            {eventsData.map((eventData, index) => (
              <InteriorDesign
                key={index} // Use a unique key for each item
                eventData={eventData.attributes} // Pass the attributes of the event
                setPopupVisible={setPopupVisible}
              />
            ))}

            {popupVisible && (
              <Popup
                eventData={selectedEventData}
                onClose={handleClosePopup}
                setPopupVisible={setPopupVisible}
              />
            )}
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
